os:
  - linux
  - osx
env:
  - SWIFT_VERSION=5.1.5
  - SWIFT_VERSION=5.3
language: generic
sudo: required
dist: bionic
osx_image: xcode12.1
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - sudo apt-get update
  - sudo apt install openssl libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev
script:
  - swift --version
  - swift build

# sudo: required
# dist: bionic
# before_install:
#   - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
#   - wget https://swift.org/builds/swift-5.3-release/ubuntu1804/swift-5.3-RELEASE/swift-5.3-RELEASE-ubuntu18.04.tar.gz
#   - tar xzf swift-5.3-RELEASE-ubuntu18.04.tar.gz
#   - export PATH=${PWD}/swift-5.3-RELEASE-ubuntu18.04/usr/bin:"${PATH}"
#   - sudo apt-get update
#   - sudo apt install openssl libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev
# script:
#   - swift --version
#   - swift build

